### ISSUE TITLE
Some filenames contain trailing whitespace

### ISSUE THREAD

**Issue by daniel-beard** [packsaddle/ruby-git_diff_parser#208]
- Was not able to look up files using `find_patch_by_file` because the filename that git_diff_parser picked up had a trailing tab character.
- Printing out the `patches.files` gave the following: `["Dangerfile", "ios/Example/Tests/Test Runners/TestRunner.swift\t"]`

**Comment by sanemat** [comment]
@daniel-beard Could you give me small example? I want to try reproducing.

**Comment by daniel-beard** [comment]
@sanemat there's a sample diff here: https://github.com/danger/danger/pull/1102 where I fixed the same issue. 

[This is the link to the git source that produces the extra tab character when a file contains a space](
https://github.com/git/git/blob/6e0cc6776106079ed4efa0cc9abace4107657abf/diff.c#L1491)

**Comment by sanemat** [comment]
Thank you for your information! I can understand this.
