### ISSUE TITLE
GitDiffParser::Patches.parse(cp932 text) raises `ArgumentError: invalid byte sequence in UTF-8`

### ISSUE THREAD

**Issue by sanemat** [packsaddle/ruby-git_diff_parser#91]
GitDiffParser::Patches.parse(cp932 text) raises `ArgumentError: invalid byte sequence in UTF-8`

here: https://github.com/packsaddle/ruby-git_diff_parser/blob/8dd67cfa619ab276635d83648480e1645ccf748a/lib/git_diff_parser/patches.rb#L22

**Comment by bootstraponline** [comment]
https://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences

**Comment by sanemat** [comment]
You should set `LANG=en_US.UTF-8`. It works fine :)

**Comment by bootstraponline** [comment]
> You should set LANG=en_US.UTF-8. It works fine :)

[It doesn't.](https://github.com/instructure/xlint/blob/caf2e3edc54421acf580c19c591b926fc1d6fa77/spec/xlint_spec.rb#L82). Comment out [the fix](https://github.com/instructure/xlint/blob/caf2e3edc54421acf580c19c591b926fc1d6fa77/lib/xlint.rb#L35) and run the spec to see.

**Comment by daniel-beard** [comment]
Also running into this issue. Can confirm that the fix listed above by @sanemat does not work.

**Comment by masa-iwasaki** [comment]
@sanemat I crated a PR for this issue. Can you take a look ?

**Comment by sanemat** [comment]
I added #147 workaround, and shipped [v3.0.0](https://github.com/packsaddle/ruby-git_diff_parser/releases/tag/v3.0.0) :tada:
